// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportVideo(arg1:string):Promise<void>;

export function GetStreamPort():Promise<number>;

export function ImportAsset():Promise<main.MediaAsset>;

export function OpenFileDialog():Promise<string>;

export function OpenWorkspace():Promise<string>;

export function RenderFramePreview(arg1:number,arg2:number,arg3:number):Promise<string>;

export function SaveWorkspace(arg1:string):Promise<void>;
