// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportVideo(arg1) {
  return window['go']['main']['App']['ExportVideo'](arg1);
}

export function GetStreamPort() {
  return window['go']['main']['App']['GetStreamPort']();
}

export function ImportAsset() {
  return window['go']['main']['App']['ImportAsset']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenWorkspace() {
  return window['go']['main']['App']['OpenWorkspace']();
}

export function RenderFramePreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderFramePreview'](arg1, arg2, arg3);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}
